// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class BookingDetail
{
    public string BookingDetailId { get; set; }

    public string BookingId { get; set; }

    public string ServiceId { get; set; }

    public int? Quantity { get; set; }

    public string TimeSlotId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual Service Service { get; set; }
}