// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Booking
{
    public string BookingId { get; set; }

    public string UserId { get; set; }

    public string StylistWorksheet { get; set; }

    public DateOnly? BookingDate { get; set; }

    public string CustomerId { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual StylistWorksheet StylistWorksheetNavigation { get; set; }

    public virtual ICollection<TransactionHistory> TransactionHistories { get; set; } = new List<TransactionHistory>();

    public virtual User User { get; set; }
}