// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Customer
{
    public string CustomerId { get; set; }

    public string UserId { get; set; }

    public string StylistId { get; set; }

    public DateOnly? Date { get; set; }

    public string BookingStatus { get; set; }

    public TimeOnly? TimeSlot { get; set; }

    public int? PointsEarned { get; set; }

    public DateOnly? EarnedDate { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Stylist Stylist { get; set; }

    public virtual User User { get; set; }
}