// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Feedback
{
    public string FeedbackId { get; set; }

    public string BookingDetail { get; set; }

    public string Comment { get; set; }

    public virtual BookingDetail BookingDetailNavigation { get; set; }
}