// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HairSalonBookingApp.Models;

public partial class HairSalonBookingAppContext : DbContext
{
    public HairSalonBookingAppContext(DbContextOptions<HairSalonBookingAppContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingDetail> BookingDetails { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<Stylist> Stylists { get; set; }

    public virtual DbSet<StylistWorksheet> StylistWorksheets { get; set; }

    public virtual DbSet<TransactionHistory> TransactionHistories { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Worksheet> Worksheets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Booking__73951ACDD18B140B");

            entity.ToTable("Booking");

            entity.Property(e => e.BookingId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("BookingID");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("CustomerID");
            entity.Property(e => e.StylistWorksheet)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("userID");

            entity.HasOne(d => d.Customer).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK__Booking__Custome__59FA5E80");

            entity.HasOne(d => d.StylistWorksheetNavigation).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.StylistWorksheet)
                .HasConstraintName("FK__Booking__Stylist__59063A47");

            entity.HasOne(d => d.User).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Booking__userID__5812160E");
        });

        modelBuilder.Entity<BookingDetail>(entity =>
        {
            entity.HasKey(e => e.BookingDetailId).HasName("PK__Booking___8136D47ABD12C40A");

            entity.ToTable("Booking_Detail");

            entity.Property(e => e.BookingDetailId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("BookingDetailID");
            entity.Property(e => e.BookingId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("BookingID");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.ServiceId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("service_id");
            entity.Property(e => e.TimeSlotId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("TimeSlotID");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("FK__Booking_D__Booki__5EBF139D");

            entity.HasOne(d => d.Service).WithMany(p => p.BookingDetails)
                .HasForeignKey(d => d.ServiceId)
                .HasConstraintName("FK__Booking_D__servi__5FB337D6");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64B8BF5B0D76");

            entity.ToTable("Customer");

            entity.Property(e => e.CustomerId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("CustomerID");
            entity.Property(e => e.BookingStatus)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StylistId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("StylistID");
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Stylist).WithMany(p => p.Customers)
                .HasForeignKey(d => d.StylistId)
                .HasConstraintName("FK__Customer__Stylis__4D94879B");

            entity.HasOne(d => d.User).WithMany(p => p.Customers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Customer__UserID__4CA06362");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Feedback__2613FDC43D7883C5");

            entity.ToTable("Feedback");

            entity.Property(e => e.FeedbackId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("feedbackID");
            entity.Property(e => e.BookingDetail)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Booking_Detail");
            entity.Property(e => e.Comment)
                .HasColumnType("text")
                .HasColumnName("comment");

            entity.HasOne(d => d.BookingDetailNavigation).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.BookingDetail)
                .HasConstraintName("FK__Feedback__Bookin__6C190EBB");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A5840669481");

            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("PaymentID");
            entity.Property(e => e.BookingId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("BookingID");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("UserID");

            entity.HasOne(d => d.Booking).WithMany(p => p.Payments)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("FK__Payment__Booking__6383C8BA");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Payment__UserID__628FA481");
        });

        modelBuilder.Entity<PaymentDetail>(entity =>
        {
            entity.HasKey(e => e.PaymentDetailId).HasName("PK__Payment___7F4E342FFB5E3011");

            entity.ToTable("Payment_Detail");

            entity.Property(e => e.PaymentDetailId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("PaymentDetailID");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Method)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PaymentId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("PaymentID");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Payment).WithMany(p => p.PaymentDetails)
                .HasForeignKey(d => d.PaymentId)
                .HasConstraintName("FK__Payment_D__Payme__66603565");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__CD98460AE5C1A022");

            entity.Property(e => e.RoleId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("roleID");
            entity.Property(e => e.RoleName)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("roleName");
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Roles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Roles__userID__6EF57B66");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("PK__Service__4550733FC2CE68FF");

            entity.ToTable("Service");

            entity.Property(e => e.ServiceId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("serviceID");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("price");
        });

        modelBuilder.Entity<Stylist>(entity =>
        {
            entity.HasKey(e => e.StylistId).HasName("PK__Stylist__A822EAC1FC132DB8");

            entity.ToTable("Stylist");

            entity.Property(e => e.StylistId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("StylistID");
            entity.Property(e => e.BaseSalary).HasColumnName("base_salary");
            entity.Property(e => e.Expertise)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Kpi).HasColumnName("KPI");
            entity.Property(e => e.Level)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("level");
            entity.Property(e => e.ProfileInfo)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("userID");

            entity.HasOne(d => d.User).WithMany(p => p.Stylists)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Stylist__userID__49C3F6B7");
        });

        modelBuilder.Entity<StylistWorksheet>(entity =>
        {
            entity.HasKey(e => e.StylistWorksheetId).HasName("PK__StylistW__0FA3CC0A5E848777");

            entity.ToTable("StylistWorksheet");

            entity.Property(e => e.StylistWorksheetId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.IsRegister).HasColumnName("is_register");
            entity.Property(e => e.Shifts)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.StylistId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("StylistID");

            entity.HasOne(d => d.Stylist).WithMany(p => p.StylistWorksheets)
                .HasForeignKey(d => d.StylistId)
                .HasConstraintName("FK__StylistWo__Styli__5441852A");
        });

        modelBuilder.Entity<TransactionHistory>(entity =>
        {
            entity.HasKey(e => e.TransactionHistoryId).HasName("PK__Transact__599D20922105EC64");

            entity.ToTable("Transaction_History");

            entity.Property(e => e.TransactionHistoryId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("TransactionHistoryID");
            entity.Property(e => e.BookingId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("BookingID");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Booking).WithMany(p => p.TransactionHistories)
                .HasForeignKey(d => d.BookingId)
                .HasConstraintName("FK__Transacti__Booki__71D1E811");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__CB9A1CDF8B965139");

            entity.ToTable("User");

            entity.Property(e => e.UserId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("userID");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Firstname)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("firstname");
            entity.Property(e => e.Lastname)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("lastname");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.Phonenumber)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("phonenumber");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("username");
        });

        modelBuilder.Entity<Worksheet>(entity =>
        {
            entity.HasKey(e => e.StylistTimeSlotDetailId).HasName("PK__Workshee__385B75A4262FE356");

            entity.ToTable("Worksheet");

            entity.Property(e => e.StylistTimeSlotDetailId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("Stylist_TimeSlot_detail_ID");
            entity.Property(e => e.ShiftId)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ShiftID");
            entity.Property(e => e.StylistStatus)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Shift).WithMany(p => p.Worksheets)
                .HasForeignKey(d => d.ShiftId)
                .HasConstraintName("FK__Worksheet__Shift__693CA210");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}