// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Payment
{
    public string PaymentId { get; set; }

    public string UserId { get; set; }

    public string BookingId { get; set; }

    public decimal? Price { get; set; }

    public DateOnly? Date { get; set; }

    public string Status { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<PaymentDetail> PaymentDetails { get; set; } = new List<PaymentDetail>();

    public virtual User User { get; set; }
}