// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class PaymentDetail
{
    public string PaymentDetailId { get; set; }

    public string PaymentId { get; set; }

    public decimal? Price { get; set; }

    public string Method { get; set; }

    public string Description { get; set; }

    public virtual Payment Payment { get; set; }
}