// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Role
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public string UserId { get; set; }

    public virtual User User { get; set; }
}