// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Stylist
{
    public string StylistId { get; set; }

    public string UserId { get; set; }

    public string Expertise { get; set; }

    public string ProfileInfo { get; set; }

    public string Level { get; set; }

    public int? BaseSalary { get; set; }

    public int? Kpi { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<StylistWorksheet> StylistWorksheets { get; set; } = new List<StylistWorksheet>();

    public virtual User User { get; set; }
}