// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class StylistWorksheet
{
    public string StylistWorksheetId { get; set; }

    public string StylistId { get; set; }

    public string Shifts { get; set; }

    public DateOnly? Date { get; set; }

    public bool? IsRegister { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual Stylist Stylist { get; set; }

    public virtual ICollection<Worksheet> Worksheets { get; set; } = new List<Worksheet>();
}