// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class TransactionHistory
{
    public string TransactionHistoryId { get; set; }

    public string BookingId { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public virtual Booking Booking { get; set; }
}