// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalonBookingApp.Models;

public partial class Worksheet
{
    public string StylistTimeSlotDetailId { get; set; }

    public string ShiftId { get; set; }

    public TimeOnly? TimeSlot { get; set; }

    public string StylistStatus { get; set; }

    public virtual StylistWorksheet Shift { get; set; }
}